management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9100
spring:
   application:
      name: shopee-api-gateway
   cloud.gateway.discovery.locator:
      enabled: true
      lower-case-service-id: true
eureka:
  client:
    serviceUrl:
         defaultZone: http://localhost:9000/shopee-naming-server/eureka
  instance.prefer-ip-address: true